export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_VIDEOGAME_ID = "GET_VIDEOGAME_ID";
export const GET_VIDEOGAME_NAME = "GET_VIDEOGAME_NAME";
export const GET_GENRES = "GET_GENRES";

export const CLEAN_DETAIL = "CLEAN_DETAIL";

//Filters
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const FILTER_BY_SOURCE = "FILTER_BY_SOURCE";

//Order
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_RATING = "ORDER_BY_RATING";
